### ISSUE TITLE
Add Repo Maintainers to CODEOWNERS file

### ISSUE THREAD

**Issue by andrewb1269** [hashgraph/awesome-hashgraph#26]
# Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Description**:

Update this repositories `.github/CODEOWNER` file to ensure that the repository maintainer
group(s) have full control of the files in this repository.

**Comment by PavelSBorisov** [comment]
Repo has no CODEOWNERS file. Closing issue.

**Comment by andrewb1269** [comment]
Will not do.
