### ISSUE TITLE
failed while running docker-compose up

### ISSUE THREAD

**Issue by huang47** [hashgraph/awesome-hashgraph#3]
## Environment

> System: Darwin MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
Docker: Docker version 17.12.0-ce, build c97c6d6

## Error

> [ERROR] Failed to execute goal on project SocketDemo: Could not resolve dependencies for project SocketDemo:SocketDemo:jar:0.0.1-SNAPSHOT: Could not find artifact SwirldsPlatform:platform:jar:0.0.1-SNAPSHOT in platform.repo (file:/opt/maven/source/socketdemo/../../data/repos/platform/) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project SocketDemo: Could not resolve dependencies for project SocketDemo:SocketDemo:jar:0.0.1-SNAPSHOT: Could not find artifact SwirldsPlatform:platform:jar:0.0.1-SNAPSHOT in platform.repo (file:/opt/maven/source/socketdemo/../../data/repos/platform/)

looks like it's stuck while finding `SwirldsPlatform:platform:jar:0.0.1-SNAPSHOT`. Please feel free to let me know if there is any further info needed so I can be more helpful

**Comment by kenthejr** [comment]
Make sure your environment is set up appropriately to include the Swirlds platform as a library reference. If you are building your new application those dependencies need to be sorted.

**Comment by kenthejr** [comment]
Please submit any further issues in the Discord server.
